### ISSUE TITLE
SOAP 1.0/1.1 and REST 1.0/1.1 - not all working consistently? 

### ISSUE THREAD

**Issue by benjamincrary** [ODM2/WOFpy#165]
@aufdenkampe @emiliom @lsetiawan @horsburgh 

I'm currently using the R library WaterML (https://cran.r-project.org/web/packages/WaterML/WaterML.pdf) to access WOF at the live EnviroDIY endpoint (http://odm2wofpy.uwrl.usu.edu:8080/odm2timeseries/). 

I am experiencing some inconsistency with the SOAP/REST protocol versions while accessing the environmental DIY data.  Certain versions (i.e. 1.0 v 1.1) of the endpoints work with certain functions, but not others. Here's what works (Y) and what doesn't (N)

Function                  | SOAP 1.0    | SOAP 1.1    |  REST 1.0    | REST 1.1
----------        | -------------    | -------------    | -------------    | -------------        
GetSites      | Y                 | Y                  | Y                 | N
GetVariables   | Y             | Y                   | N                 | Y, w/ warning
GetValues      | Y             | Y                   | N                 | Y
GetSiteInfo   | Y             | N                   | N                  | N

For example, endpoints for SOAP 1.0, SOAP 1.1, and REST 1.0 all work with the  GetSites command. REST 1.1 does not work. 

Alternately, endpoints for SOAP 1.0, SOAP 1.1, and REST 1.1 all work for the GetVariables command. Rest 1.0 does not work. 

I randomly compared to the Ipswich River Watershed Association (http://hiscentral.cuahsi.org/pub_network.aspx?n=247) SOAP endpoints with the WaterML package, and the same inconsistency is not exhibited. Thus, there may be an issue with the WOFpy setup. 

For additional context, I've uploaded an R jupyter notebook here:
https://github.com/BiG-CZ/BiG-CZ-Toolbox/blob/master/ipynotebooks/Endpoint%20Tests%20with%20WaterML%2C%20WOF.ipynb 

- Thanks

**Comment by lsetiawan** [comment]
Thanks @benjamincrary for this report, we will definitely look into what's going on. 

In the mean time, I have tried going to the SOAP end point to start the testing and running into an error when using [`ulmo`](https://github.com/ulmo-dev/ulmo) in Python.

@emiliom I tried requesting the SOAP end point for WOF 1.1 GetSites with `ulmo` and I am getting an error. 

```python
server = 'http://odm2wofpy.uwrl.usu.edu:8080/odm2timeseries/soap/cuahsi_1_1/.wsdl'
ulmo.cuahsi.wof.get_sites(server)
```

<details>
<summary>Error</summary>

```python
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-22-6320b25e2dce> in <module>()
      1 server = "http://odm2wofpy.uwrl.usu.edu:8080/odm2timeseries/soap/cuahsi_1_1/.wsdl"
----> 2 ulmo.cuahsi.wof.get_sites(server)

/home/lsetiawan/miniconda/envs/wofpy/lib/python2.7/site-packages/ulmo/cuahsi/wof/core.pyc in get_sites(wsdl_url, suds_cache)
     58         response = suds_client.service.GetSites('')
     59         response_buffer = io.BytesIO(util.to_bytes(response))
---> 60         sites = waterml.v1_1.parse_site_infos(response_buffer)
     61 
     62     return dict([

/home/lsetiawan/miniconda/envs/wofpy/lib/python2.7/site-packages/ulmo/waterml/v1_1.pyc in parse_site_infos(content_io)
      7     """parses site_infos out of a waterml file; content_io should be a file-like object"""
      8     return common.parse_site_infos(
----> 9         content_io, WATERML_V1_1_NAMESPACE, site_info_names=['siteInfo', 'sourceInfo'])
     10 
     11 

/home/lsetiawan/miniconda/envs/wofpy/lib/python2.7/site-packages/ulmo/waterml/common.pyc in parse_site_infos(content_io, namespace, site_info_names)
    106         site_info_dicts = [
    107             _parse_site_info(site_info_element, namespace)
--> 108             for site_info_element in site_info_elements
    109         ]
    110         site_infos.update(dict([(d['code'], d) for d in site_info_dicts]))

/home/lsetiawan/miniconda/envs/wofpy/lib/python2.7/site-packages/ulmo/waterml/common.pyc in _parse_site_info(site_info, namespace)
    322         (util.camel_to_underscore(note.attrib['title'].replace(' ', '')),
    323             note.text)
--> 324         for note in site_info.findall(namespace + 'note')
    325     ])
    326     if notes:

src/lxml/lxml.etree.pyx in lxml.etree._Attrib.__getitem__ (src/lxml/lxml.etree.c:70679)()

KeyError: 'title'
```

</details>


Is there any known problem with `ulmo` interaction with get_sites in postgresql? I tried connecting to our copy of Envirodiy in http://54.186.36.247:8080/postgresqlodm2timeseries/soap/cuahsi_1_1/.wsdl and get the same thing. No problem with MySQL LBR though.

**Comment by emiliom** [comment]
@benjamincrary, wow, thanks for that extensive assessment! Are you already a WaterML user? Thanks also for putting together a Jupyter notebook **and** uploading it to a useful and relevant BiG-CZ repo! It's great to see an R Jupyter notebook in action.

@lsetiawan, thanks for your follow up.

I'll start by stepping back a bit. There are three important issues/considerations here:
1. Testing was done on a specific WOFpy deployment (EnviroDIY on a USU server) that's not managed by @lsetiawan or me, so we can't vouch for every aspect of it.
2. WOF/WaterML 1.0 vs 1.1
3. SOAP vs REST

**I'll start with the easiest, # 2:** we have not done much testing on WOF/WaterML 1.0 for ODM2 timeseries sources (See the [release notes](https://github.com/ODM2/WOFpy/releases/tag/v2.1.0b0): "most testing focused on WOF/WaterML 1.1 only. Double-checked that WOF/WaterML 1.0 and WaterML 2 works, but did not go further than that"). So I'm not even going to try to say anything further about failures with 1.0. It'd be good to keep a running list (a github issue) of known problems, but otherwise supporting 1.0 for ODM2 data sources is low in the priority stack.

**# 1, use of EnviroDIY USU endpoint.** It's hard to separate WOFpy general issues from implementation/instance issues. I think the kind of terrific, thorough assessments you've done should start with canonical WOFpy endpoints that @lsetiawan control and can vouch for or investigate directly. That'd give us a good assessment on WOFpy proper. Then you can do the same thing on your specific endpoint of interest (EnviroDIY @ USU) and see what's different.

We've tested REST 1.1 responses thoroughly and I'm positive all the responses work. Our two live WOFpy instances are:
- http://54.186.36.247:8080/mysqlodm2timeseries/
- http://54.186.36.247:8080/postgresqlodm2timeseries/

The second is actually a static, older version of EnviroDIY that we used for testing and debugging. Using that instance, I tested manually the REST 1.1 requests you reported as failing (`GetSites` and `GetSiteInfo`), and they both worked. Actually, I also tested [GetSites on the USU REST 1.1 endpoint](http://odm2wofpy.uwrl.usu.edu:8080/odm2timeseries/rest/1_1/GetSites), and it too worked!

**# 3, SOAP vs REST.** We probably haven't done enough regular SOAP testing, though I *think* some of our continuous-integration ODM2 tests do use SOAP. But again, I'd start with one of our two canonical endpoints. @lsetiawan, thanks for that ulmo test. I'm not aware of SOAP problems, but we should definitely investigate what you've found. I found something similar using http://soapclient.com/soaptest.html. Please open a new github issue so we can look into it. But I can't imagine why there'd be a problem with SOAP and not with REST that's tied to the database type (postgresql vs mysql)! SOAP and REST are just the request protocols; the interactions with the database backend should be the same regardless of the protocol used.

**Side note:** @lsetiawan, I noticed that @benjamincrary had a `GetVariables` request in his test matrix, but our auto-generated WOFpy REST sample page (eg, http://54.186.36.247:8080/postgresqlodm2timeseries/rest_1_1/) doesn't include `GetVariables`. We should add it -- please look into it. Though it's worth noting that `GetVariableInfo` w/o parameters seems to be identical to `GetVariables`; in fact, the latter seems to be an alias for the former: the response for the latter includes this:
```xml
<queryInfo>
    <criteria MethodCalled="GetVariableInfo"/>
    <note show="Web Service"/>
</queryInfo>
```

Sorry for the long response!

**Comment by lsetiawan** [comment]
> Side note: @lsetiawan, I noticed that @benjamincrary had a GetVariables request in his test matrix, but our auto-generated WOFpy REST sample page (eg, http://54.186.36.247:8080/postgresqlodm2timeseries/rest_1_1/) doesn't include GetVariables. We should add it -- please look into it.

@emiliom Should I replace `GetVariableInfo` with `GetVariables` or keep `GetVariableInfo` and add `GetVariables`? Thanks.

**Comment by emiliom** [comment]
> Should I replace GetVariableInfo with GetVariables or keep GetVariableInfo and add GetVariables?

Keep GetVariableInfo and add GetVariables

**Comment by emiliom** [comment]
FYI, @lsetiawan and I are making good progress on testing against our MySQL and PostgreSQL WOFpy instances, SOAP vs REST (1.1 only), in issue #168. We'll report back with solid findings probably by the end of Monday.

**Comment by emiliom** [comment]
A new release [v2.2.0](https://github.com/ODM2/WOFpy/releases/tag/v2.2.0) is just out, with some bug fixes that originated from @benjamincrary's assessment -- plus many other fixes and enhancements. 

pip and conda packages will be ready by Friday, possibly today.

FYI, we created a Python Jupyter notebook inspired by your tests: [docs/WOFpy_ODM2_SOAPandREST_Tests.ipynb](https://github.com/ODM2/WOFpy/blob/master/docs/WOFpy_ODM2_SOAPandREST_Tests.ipynb). It was very helpful for debugging. Right now it shows some failures from the last time we ran it, but we (@lsetiawan?) will try to update it after the new WOFpy release has been deployed on our live AWS sample endpoints.

It'd be great if these tests could be re-run. But please coordinate with us first to better control the test conditions. Thanks again!
