### ISSUE TITLE
SOAP Request not working on Postgresql?

### ISSUE THREAD

**Issue by lsetiawan** [ODM2/WOFpy#168]
This issue follows up with https://github.com/ODM2/WOFpy/issues/165#issuecomment-323408861

> **# 3, SOAP vs REST**. We probably haven't done enough regular SOAP testing, though I think some of our continuous-integration ODM2 tests do use SOAP. But again, I'd start with one of our two canonical endpoints. @lsetiawan, thanks for that ulmo test. I'm not aware of SOAP problems, but we should definitely investigate what you've found. I found something similar using http://soapclient.com/soaptest.html ... SOAP and REST are just the request protocols; the interactions with the database backend should be the same regardless of the protocol used.

**Comment by emiliom** [comment]
Thanks. If this is a real problem, it definitely would be important to address it and fix it soon, ideally for the next release.

We should check whether the SOAP 1.1 problem is limited to `GetSites`, or if it occurs with other requests as well.

**Comment by lsetiawan** [comment]
SOAP and REST testing for WaterML 1.1 between Postgresql and MySQL can be found here. https://gist.github.com/lsetiawan/5450e69df1a5257545aec2c29c8696d3

@emiliom Let me know if I need to tweak or add anything. Thanks.

**Comment by emiliom** [comment]
Nice, thanks!

A comment on the REST 1.1 tests only: in your code, failures are seen in both the postgresql and mysql endpoints. Postgresql `GetSites` fails. BUT, this url for the GetSites request works just fine: http://54.186.36.247:8080/postgresqlodm2timeseries/rest/1_1/GetSites. For the mysql endpoint, the `GetSiteInfo` test fails, but the equivalent url for the request works just fine: http://54.186.36.247:8080/mysqlodm2timeseries/rest/1_1/GetSites?site=mysqlodm2timeseries:USU-LBR-Mendon

So, the problems are probably with the ulmo parsing in your code, and therefore potentially with the content of some of the responses. As a next step, can you change the try/except blocks to capture and print out the specific errors (what module/line is causing an error, and what's the error)?

Same thing with `GetVariableInfo`, which fails on both endpoints. But `GetVariables` works with both endpoints. Hmm.

Wait, I just noticed something in your gist: Under the SITES test, you have the ulmo parsing statement `sites = ulmo.waterml.v1_1.parse_site_infos(response_buffer)`, and under the SITE INFO test you have `siteinfo = ulmo.waterml.v1_1.parse_sites(response_buffer)`. Looks like they're flipped.

**Comment by lsetiawan** [comment]
> Wait, I just noticed something in your gist: Under the SITES test, you have the ulmo parsing statement sites = ulmo.waterml.v1_1.parse_site_infos(response_buffer), and under the SITE INFO test you have siteinfo = ulmo.waterml.v1_1.parse_sites(response_buffer). Looks like they're flipped.

This seems weird to me too, but I am referring straight from how `ulmo` is doing things. [`get_sites`](https://github.com/ulmo-dev/ulmo/blob/master/ulmo/cuahsi/wof/core.py#L60), [`get_site_info`](https://github.com/ulmo-dev/ulmo/blob/master/ulmo/cuahsi/wof/core.py#L105). Thanks.

**Comment by emiliom** [comment]
> This seems weird to me too, but I am referring straight from how ulmo is doing things. get_sites, get_site_info

Ok. Yeah, there must be historical reasons for those misleading ulmo function names.

I examined your notebook more closely and found errors in the print statements of your REST testing for `GetSiteInfo`, `GetVariableInfo` and `GetValues`. You reused the code from the SOAP tests probably w/o checking it first :stuck_out_tongue_winking_eye:. For example, for GetSiteInfo:
```python
# Your original statement:
print(siteinfo['site_property'])
# Corrected statement:
print(siteinfo[sitecode.split(':')[1]]['site_property'])
```

You were using the ulmo response dictionaries incorrectly. That's why the mysql tests were also resulting in errors for those 3 requests (since your try-except error catching is non-specific, the error could come from any of the 4 lines). I've uploaded to the wofpy repo a corrected and slightly refactored version of the notebook, [here](/ODM2/WOFpy/blob/master/docs/WOFpy_ODM2_SOAPandREST_Tests.ipynb).

All the mysql REST tests are now successful.

HOWEVER ... while running initial wofpy test requests, the PostgreSQL database became dysfunctional, returning the `Can't reconnect until invalid transaction is rolled back` exception we've seen before with PostgreSQL. *I guess we still need to look into why that's still happening with PostgreSQL!* So, by the time I had this notebook finalized, the PostgreSQL endpoint was no longer working. Still, looking at the results of your notebook in light of my fixes to the REST tests, it looks to me like all PostgreSQL requests were working, except possibly `GetSites` with SOAP and maybe REST; or with the ulmo parsing of both GetSites and GetSiteInfo, which would likely be due to actual encoding bugs in the WOFpy responses.

Please restart the PostgreSQL wofpy server when you get a chance, so we can continue testing.

**Comment by emiliom** [comment]
@lsetiawan, I'm copying here your prior error report on `GetSites`, as it has helpful info for debugging the PostgreSQL responses. It makes me suspect that there may be an error coming from an idiosyncracy in the content of the EnviroDIY database, not an actual bug in PostgreSQL handling per se. Still, we need to track this down.

> I tried requesting the SOAP end point for WOF 1.1 GetSites with `ulmo` and I am getting an error. 

```python
server = 'http://odm2wofpy.uwrl.usu.edu:8080/odm2timeseries/soap/cuahsi_1_1/.wsdl'
ulmo.cuahsi.wof.get_sites(server)
```

<details>
<summary>Error</summary>

```python
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-22-6320b25e2dce> in <module>()
      1 server = "http://odm2wofpy.uwrl.usu.edu:8080/odm2timeseries/soap/cuahsi_1_1/.wsdl"
----> 2 ulmo.cuahsi.wof.get_sites(server)

/home/lsetiawan/miniconda/envs/wofpy/lib/python2.7/site-packages/ulmo/cuahsi/wof/core.pyc in get_sites(wsdl_url, suds_cache)
     58         response = suds_client.service.GetSites('')
     59         response_buffer = io.BytesIO(util.to_bytes(response))
---> 60         sites = waterml.v1_1.parse_site_infos(response_buffer)
     61 
     62     return dict([

/home/lsetiawan/miniconda/envs/wofpy/lib/python2.7/site-packages/ulmo/waterml/v1_1.pyc in parse_site_infos(content_io)
      7     """parses site_infos out of a waterml file; content_io should be a file-like object"""
      8     return common.parse_site_infos(
----> 9         content_io, WATERML_V1_1_NAMESPACE, site_info_names=['siteInfo', 'sourceInfo'])
     10 
     11 

/home/lsetiawan/miniconda/envs/wofpy/lib/python2.7/site-packages/ulmo/waterml/common.pyc in parse_site_infos(content_io, namespace, site_info_names)
    106         site_info_dicts = [
    107             _parse_site_info(site_info_element, namespace)
--> 108             for site_info_element in site_info_elements
    109         ]
    110         site_infos.update(dict([(d['code'], d) for d in site_info_dicts]))

/home/lsetiawan/miniconda/envs/wofpy/lib/python2.7/site-packages/ulmo/waterml/common.pyc in _parse_site_info(site_info, namespace)
    322         (util.camel_to_underscore(note.attrib['title'].replace(' ', '')),
    323             note.text)
--> 324         for note in site_info.findall(namespace + 'note')
    325     ])
    326     if notes:

src/lxml/lxml.etree.pyx in lxml.etree._Attrib.__getitem__ (src/lxml/lxml.etree.c:70679)()

KeyError: 'title'
```

</details>

**Comment by lsetiawan** [comment]
>  I've uploaded to the wofpy repo a corrected and slightly refactored version of the notebook, here.

Thanks for doing that. 

> while running initial wofpy test requests, the PostgreSQL database became dysfunctional, returning the Can't reconnect until invalid transaction is rolled back exception we've seen before with PostgreSQL. I guess we still need to look into why that's still happening with PostgreSQL! 

Yea. I'll look into what's going on. Thanks.

**Comment by lsetiawan** [comment]
All of the errors seen during SOAP and REST testing are caused by `KeyError`.

```python
*** KeyError:
Traceback (most recent call last):
  File "<ipython-input-7-53857f5fcb02>", line 23, in <module>
    siteinfo = ulmo.cuahsi.wof.get_site_info(url, site_code=sitecode)
  File "//anaconda/envs/uwapl_em_mc_1aui/lib/python2.7/site-packages/ulmo/cuahsi/wof/core.py", line 105, in get_site_info
    sites = waterml.v1_1.parse_sites(response_buffer)
  File "//anaconda/envs/uwapl_em_mc_1aui/lib/python2.7/site-packages/ulmo/waterml/v1_1.py", line 21, in parse_sites
    return common.parse_sites(content_io, WATERML_V1_1_NAMESPACE)
  File "//anaconda/envs/uwapl_em_mc_1aui/lib/python2.7/site-packages/ulmo/waterml/common.py", line 124, in parse_sites
    for site_element in site_elements]
  File "//anaconda/envs/uwapl_em_mc_1aui/lib/python2.7/site-packages/ulmo/waterml/common.py", line 281, in _parse_site
    site_dict = _parse_site_info(site.find(namespace + 'siteInfo'), namespace)
  File "//anaconda/envs/uwapl_em_mc_1aui/lib/python2.7/site-packages/ulmo/waterml/common.py", line 324, in _parse_site_info
    for note in site_info.findall(namespace + 'note')
  File "src/lxml/lxml.etree.pyx", line 2452, in lxml.etree._Attrib.__getitem__ (src/lxml/lxml.etree.c:68625)
KeyError: 'title'
```

**Comment by emiliom** [comment]
Yeah. And here's an interesting difference in REST 1.1 `GetSiteInfo` responses for the the mysql and postgresql sites in your test, in the `<siteInfo>` block:

**[mysql:](http://54.186.36.247:8080/mysqlodm2timeseries/rest/1_1/GetSiteInfo?site=mysqlodm2timeseries:USU-LBR-Mendon)**
```xml
<siteProperty name="Site Comments">
Located below county road bridge at Mendon Road crossing
</siteProperty>
```
Has `siteProperty` element, and no `note` element.

**[postgresql:](http://54.186.36.247:8080/postgresqlodm2timeseries/rest/1_1/GetSiteInfo?site=postgresqlodm2timeseries:160065_4vars)**
```xml
<note/>
```
Has no `siteProperty` element, and an empty `note` element. *See the reference to `for note in site_info.findall(namespace + 'note')` in the error message you pasted (and in the notebook).*

The LBR mysql DB must have an ODM2 sampling feature attribute (the `description` column?) that gets mapped to `siteProperty@name="Site Comments"`. In the EnviroDIY postgresql DB, that same ODM2 attribute must be null or a blank character, but for some reason it's being mapped to an empty `note` element and no `siteProperty` element. That's causing the problem, somehow. The problem must start in the DAO code, but the failure happens in `waterml/common.py`. It is a response content problem after all, and that's why I had never noticed it in the manual REST responses that I simply inspected on a browser.

Hopefully that information can help you identify the exact problem and address it.

**Comment by emiliom** [comment]
Forgot to add that I *think* `note` is from WaterML 1.0 and `siteProperty` was introduced in 1.1 to replace `note`. But you'll have to check the WaterML 1.1 documentation to confirm.

**Comment by lsetiawan** [comment]
@emiliom Those comments helped a lot! I found the problem [here](https://github.com/ODM2/WOFpy/blob/master/wof/core_1_1.py#L682). Should be `add_siteProperty()`. 

## Note from WaterML1.1 Docs:
CHANGES FROM WATERML 1.0
siteType - This describes the environment of the site, eg stream, estuary, spring
siteProperty - delinates properties of the Site in an OGC like manner. Ideally, site properties
should have a URL which is derived from an ontology, or a url reference describing the property.
note - depreciated. Use siteProperty.

## Question
My question is `siteProperty` required? 

## Notes
I am getting a `KeyError` `name` when `siteProperty` is empty. When I get rid of `siteProperty` from the resulting XML, and use ulmo again, the request works for both SOAP and REST.

**Comment by lsetiawan** [comment]
Based on the [WaterML 1.1 Schema](http://his.cuahsi.org/documents/cuahsiTimeSeries_v1_1.xsd)

``` xml
<xsi:element minOccurs="0" maxOccurs="unbounded" name="siteProperty" type="PropertyType"/>
```

`siteProperty` `minOccurs` is 0, so I think I can just not list `siteProperty` if there's no values for it.

**Comment by emiliom** [comment]
Excellent!!

> siteProperty minOccurs is 0, so I think I can just not list siteProperty if there's no values for it.

Yup, that's the answer!

BTW, another conclusion from all this research is that the source problem has nothing to do with postgresql vs mysql. It's all about the bug in wofpy and empty database attributes that may populate `siteProperty` (from what I've seeing, I'm guessing the ODM2 timeseries DAO is not currently parsing state and county, so that comment is the only attribute that could populate `siteProperty`).

**Comment by lsetiawan** [comment]
> I'm guessing the ODM2 timeseries DAO is not currently parsing state and county, so that comment is the only attribute that could populate siteProperty)

Correct. [It doesn't seem like it](https://github.com/ODM2/WOFpy/blob/master/wof/examples/flask/odm2/timeseries/sqlalch_odm2_models.py#L57). I'll see if I can fix this. Thanks for the help debugging 😄

**Comment by lsetiawan** [comment]
I am not sure where to grab `County` from, but `State` can be obtained from [`Affiliations.PrimaryAddress`](http://odm2.github.io/ODM2/schemas/ODM2_Current/columns/ODM2Core_Affiliations_PrimaryAddress.html)

**Comment by emiliom** [comment]
Ignore County. And even State is not important right now. Fixing the bug
ASAP is far more important.

On Aug 21, 2017 1:23 PM, "Landung Setiawan" <notifications@github.com>
wrote:

I am not sure where to grab County from, but State can be obtained from
Affiliations.PrimaryAddress
<http://odm2.github.io/ODM2/schemas/ODM2_Current/columns/ODM2Core_Affiliations_PrimaryAddress.html>

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/ODM2/WOFpy/issues/168#issuecomment-323843362>, or mute
the thread

**Comment by lsetiawan** [comment]
After PR #171, this problem doesn't occur anymore. Closing this issue.
