### ISSUE TITLE
Update Docs

### ISSUE THREAD

**Issue by valentinedwv** [ODM2/WOFpy#22]
Changes to documentation

**Comment by valentinedwv** [comment]
@emiliom added a Readme.md doc. 
Thanks.

**Comment by valentinedwv** [comment]
I updated the doc and pushed to pydocs.
Still needs more work

**Comment by emiliom** [comment]
Is this the "pydocs" push? http://pydoc.net/Python/WOFpy/0.1.1-alpha/ (that looks old, before all the work you and Choonhan have done).
Or is it something else?

BTW, it looks like readme.txt is an rst file. Maybe it would've been best if I had changed the file extension and edited that file instead of creating a new/copy as a markdown file (README.md). But I don't know rst syntax and creating the md version was easier. It's a start.

**Comment by valentinedwv** [comment]
I pushed to http://pythonhosted.org/WOFpy/

Pydoc must be pulling from original

**Comment by emiliom** [comment]
Ah, pythonhosted.org. Great. I've updated README.md to include a prominent link to those docs. Thanks.

**Comment by aufdenkampe** [comment]
The need to release documentation has now been folded into #128
