### ISSUE TITLE
ODM2: GetSiteInfo

### ISSUE THREAD

**Issue by valentinedwv** [ODM2/WOFpy#8]
Works with 
*SDSC:LR_TWDEF_C*

fails with:
*SDSC:OBI*
```
Exception: Site,'SDSC:Obi', Not Found
```
Is this because this is a measuement site, or other reason?

**Comment by emiliom** [comment]
A couple of things are probably going on here. Obi is a Site SamplingFeature (SF) in my "Marchantaria" use case. The Marchantaria dataset uses Site and Specimen SamplingFeatures, and both of those are being [exposed via the GetSites request](http://sis-devel.cloudapp.net:8080/GetSites); eg, compare the `GetSites` responses for the [Marchantaria Site SF (SDSC:march)](http://sis-devel.cloudapp.net:8080/GetSites?site=SDSC:march) vs the [SDSC:sta1036exp1300smp436_dissgas Specimen SF](http://sis-devel.cloudapp.net:8080/GetSites?site=SDSC:sta1036exp1300smp436_dissgas). Corresponding `GetSiteInfo` requests fail for *SDSC:march* but work as expected for *SDSC:sta1036exp1300smp436_dissgas*. The parent-child SF relationship between the two is not captured. Note that it **is** captured in the ODM2 REST services.

It looks like GetSiteInfo is returning an error when there are no results associated with the SamplingFeature, as is the case with both SDSC:march and SDSC:obi.

Another wrinkle is that the Marchantaria dataset includes many Site SF's that are actually not associated with any results, directly or via children SF's. Currently, the only Site SF associated with results (via children Specimen SF's) is SDSC:march. That can cause confusion. But if you have graceful error catching for WOF sites that have no series, that shouldn't be a problem.

Given the limitations and focus of WOF and WaterML 1.x on sites and time series, I would suggest:

1. Specimen SF's should not be exposed as WOF sites. If they have a parent Site SF, only the parent SF should be exposed as a WOF site.
2. The parent-child specimen-site SF relationship should be enabled. GetSiteInfo, GetVariableInfo and GetValues requests on a WOF site will return corresponding series and values information for the ODM2 Site SF and its children Specimen SF.

This does mean that ODM2 results associated with a Specimen SF that in turn has no parent Site SF will not be exposed via WOF. That seems fine to me, since WOF is for time series. But maybe others should pipe in.

I'm looping in @horsburgh for his general input.

**Comment by valentinedwv** [comment]
For WOF, only sites with Results need to be exposed in GetSites, and GetSiteInfo.

**Comment by emiliom** [comment]
> For WOF, only sites with Results need to be exposed in GetSites, and GetSiteInfo

Yes, but for-specimen based measurement results, just keep in mind that Sites may be associated with results via the parent-child Site > Specimen relationship. If that's what you meant, we're on the same page.

**Comment by cdesyoun** [comment]
In order to get site information with sampling features for marchanteria datasets, when querying sites with samplingfeatures, I joined "relatedfeatures" table which Emilio described before. In this table, all of sampling features point to one related sampling feature which has a site information.
As Emilio mentioned above, all of sampling features do not have results yet.
So, do you want to just show sites with results?

**Comment by horsburgh** [comment]
I think we will quickly get to the point with WOF and WaterML 1.1 on top of ODM2 that we will see limitations with respect to representing the metadata for specimen-based data.  Do we want to just limit WOF for ODM2 to deliver only Time Series Results?

**Comment by klehnert55** [comment]
I think that would be most reasonable.

On 10/8/15 13:00 PM, Jeff Horsburgh wrote:
>
> I think we will quickly get to the point with WOF and WaterML 1.1 on 
> top of ODM2 that we will see limitations with respect to representing 
> the metadata for specimen-based data. Do we want to just limit WOF for 
> ODM2 to deliver only Time Series Results?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/ODM2/WOFpy/issues/8#issuecomment-146624064>.
>

-- 
Dr. Kerstin Lehnert
Director, Interdisciplinary Earth Data Alliance
Director, EarthChem
President, IGSN e.V.

Lamont-Doherty Earth Observatory
Columbia University
Palisades, NY, 10964
(845) 365-8506
http://www.iedadata.org
http://www.earthchem.org
http://www.igsn.org

**Comment by klehnert55** [comment]
We should take a look at the EarthChemXML if it is at all helpful for 
exchange of sample-based data.

On 10/8/15 13:00 PM, Jeff Horsburgh wrote:
>
> I think we will quickly get to the point with WOF and WaterML 1.1 on 
> top of ODM2 that we will see limitations with respect to representing 
> the metadata for specimen-based data. Do we want to just limit WOF for 
> ODM2 to deliver only Time Series Results?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/ODM2/WOFpy/issues/8#issuecomment-146624064>.
>

-- 
Dr. Kerstin Lehnert
Director, Interdisciplinary Earth Data Alliance
Director, EarthChem
President, IGSN e.V.

Lamont-Doherty Earth Observatory
Columbia University
Palisades, NY, 10964
(845) 365-8506
http://www.iedadata.org
http://www.earthchem.org
http://www.igsn.org

**Comment by emiliom** [comment]
> We should take a look at the EarthChemXML if it is at all helpful for exchange of sample-based data.

Absolutely, @klehnert55!
But that discussion should be started as a separate github issue, even a separate github repo or an initial email and/or phone discussion. If we go too far addressing that topic in this specific github issue (and [github repo](https://github.com/ODM2/WOFpy)) that's all about WaterOneFlow, it'll get diluted.

**Comment by emiliom** [comment]
@horsburgh said:
> I think we will quickly get to the point with WOF and WaterML 1.1 on top of ODM2 that we will see limitations with respect to representing the metadata for specimen-based data. Do we want to just limit WOF for ODM2 to deliver only Time Series Results?

That's a reasonable, pragmatic and probably wise approach to follow initially. 

In practice, it will mean that my Marchantaria use case will be excluded. That's fine. Once we work out all kinks with Time Series Results for ODM2 WOF, maybe we can revisit Marchantaria and similar use cases currently present in CZO Central ODM 1.x databases, mostly consisting of semi-regular water chemistry measurements based on sample collection (typically water, and dissolved constituents) and a mix of in-situ measurements and lab analyses on samples; these are best represented as ODM2 Measurement Results to take full advantage of ODM2 capabilities, but for data exploration and analysis they're often best addressed as time series (ie, WOF & WaterML 1.x have been used with that type of data, and are in fact convenient). [See the description of the Marchantaria use case for some discussion on this.](https://github.com/ODM2/ODM2/tree/master/usecases/marchantariats)

**Comment by valentinedwv** [comment]
Choonhan/Stephanie,
If sites and specimens inherit from SamplingFeature, rather than base does one get the appropriate feature?

**Comment by cdesyoun** [comment]
David, @valentinedwv I am not sure what you mean. Sites, Specimens, and SamplingFeaturess(SF) have the primary key as the sampling feature id. Depending on the relationship, I think one can have the appropriate feature.

Emilio, @emiliom, I updated with your suggestions for marchanteria data into test site.
Since there is only one site as the parent sampling feature, the res of child sampling features are not displayed. But, I enabled them with one parent in behind.
Please review it. 
REST: http://sis-devel.cloudapp.net:8080/
SOAP: http://sis-devel.cloudapp.net:8080/soap/wateroneflow.wsdl

**Comment by emiliom** [comment]
@cdesyoun, thanks! Just be aware that it's possible you're hard-wiring some assumptions based on my use case, which may not be true for other Measurements-based use cases. But if that works for you in terms of getting the WOFpy-ODM2 adaptation going, that sounds good.

I tried the REST endpoint. I can get to http://sis-devel.cloudapp.net:8080, but from there, the service requests are very unstable. I've managed to get a few successful responses, but most of the time it hung; on one case I waited until I got this error, on a GetSites request:
```
sqlalchemy.exc.OperationalError
OperationalError: (OperationalError) could not connect to server: Connection timed out
	Is the server running on host "sis-devel.cloudapp.net" (104.42.4.16) and accepting
	TCP/IP connections on port 5432?
```
With the SOAP endpoint, I could see the WSDL XML on a browser, but issuing a SOAP request also resulted in a timed out error.

So, right now it's too unstable to do any testing.

On an earlier message you said you also had "part of Jeff’s LBR time series data which loads one of YODA files for this service".  Is that time series all set up for testing, too? (once the server is more stable)

**Comment by cdesyoun** [comment]
Emilio, @emiliom , I am so sorry for this trouble. It is my mistake for misconfiguration for the database.
Now it is OK for running the server. Please review it again.

**Comment by cdesyoun** [comment]
In addition, for the jeff's multiple time series data, site-samplingfeature code is "LR_TWDEF_C", and variables are "AirtTemp_Avg", "AirtTemp_Min", "AirtTemp_Max".

**Comment by cdesyoun** [comment]
For machantaria data, I did query measurement result values with related features if there are no data values when querying measurement result value with sampling feature.

**Comment by emiliom** [comment]
Perfect. Now all responses are fast, and I haven't gotten any failures. Thanks. Unfortunately, I don't think I'll be able to spend more time on this today. I already have a couple of comments, but I'll wait until I have more time to review this, early next week.

Thanks for the info on Jeff's time series. Great. GetSites does, in fact, return only two sites (ODM2WofPy:march and ODM2WofPy:LR_TWDEF_C), so that matches what you said.

Quick question: is this WOFpy service using exactly the same ODM2 database backend as the ODM2 REST services? For my assessment, I'd like to be able to compare responses between, say:
http://sis-devel.cloudapp.net:80/sites/samplingfeatureCode/LR_TWDEF_C/?format=xml
and
http://sis-devel.cloudapp.net:8080/GetSites?site=ODM2WofPy:LR_TWDEF_C

**Comment by cdesyoun** [comment]
Great! Yes, I am using the sample ODM2 database for both services on the back end.

**Comment by valentinedwv** [comment]
Thinking modifying the 'model' to use inheritance

**Comment by valentinedwv** [comment]
Closing
